version: "3"
services:
  kong-migration:
    image: kong/kong-gateway:3.1.1.1
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: db
      KONG_PG_USER: postgres
      KONG_PG_PASSWORD: secret
      KONG_PASSWORD: test
    command: kong migrations bootstrap
    networks:
      - tunas-network
  
  kong:
    image: kong/kong-gateway:3.1.1.1
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: db
      KONG_PG_USER: postgres
      KONG_PG_PASSWORD: secret
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    networks:
      - tunas-network
    links:
      - kong-migration

  konga:
    image: pantsel/konga
    environment:
      NODE_ENV: development
      TOKEN_SECRET: ualalulili
    ports:
      - "1337:1337"
    networks:
      - tunas-network
    links:
      - kong

networks:
  tunas-network:
    external: true
